import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:task/core/app_export.dart';

class AppTheme {
  AppTheme._();

  static ThemeData get lightTheme => _theme(_lightColorScheme);

  static ThemeData get darkTheme => _theme(_darkColorSchema);

  static ThemeData _theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    colorScheme: colorScheme,
    brightness: colorScheme.brightness,
    textTheme: GoogleFonts.sanchezTextTheme().copyWith().apply(
      bodyColor: colorScheme.onSurface,
      displayColor: colorScheme.onSurface,
    ),
    // elevatedButtonTheme: _elevatedButtonTheme,
    // inputDecorationTheme: _inputDecorationTheme,
  );

  static ColorScheme get _lightColorScheme => ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff003540),
    surfaceTint: Color(0xff346572),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff174c59),
    onPrimaryContainer: Color(0xff8bbbca),
    secondary: Color(0xff506167),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffd0e3ea),
    onSecondaryContainer: Color(0xff54656b),
    tertiary: Color(0xff3b284a),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff523e62),
    onTertiaryContainer: Color(0xffc4abd5),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfff9f9fa),
    onSurface: Color(0xff191c1d),
    onSurfaceVariant: Color(0xff40484b),
    outline: Color(0xff71787b),
    outlineVariant: Color(0xffc0c8cb),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2e3132),
    inversePrimary: Color(0xff9dcede),
    primaryFixed: Color(0xffb9eafa),
    onPrimaryFixed: Color(0xff001f27),
    primaryFixedDim: Color(0xff9dcede),
    onPrimaryFixedVariant: Color(0xff184d5a),
    secondaryFixed: Color(0xffd3e6ec),
    onSecondaryFixed: Color(0xff0c1e23),
    secondaryFixedDim: Color(0xffb7cad0),
    onSecondaryFixedVariant: Color(0xff38494f),
    tertiaryFixed: Color(0xfff1daff),
    onTertiaryFixed: Color(0xff251335),
    tertiaryFixedDim: Color(0xffd7bde8),
    onTertiaryFixedVariant: Color(0xff533f63),
    surfaceDim: Color(0xffd9dadb),
    surfaceBright: Color(0xfff9f9fa),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff3f4f4),
    surfaceContainer: Color(0xffedeeef),
    surfaceContainerHigh: Color(0xffe7e8e9),
    surfaceContainerHighest: Color(0xffe2e2e3),
  );

  static ColorScheme get _darkColorSchema => ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff9dcede),
    surfaceTint: Color(0xff9dcede),
    onPrimary: Color(0xff003641),
    primaryContainer: Color(0xff174c59),
    onPrimaryContainer: Color(0xff8bbbca),
    secondary: Color(0xffb7cad0),
    onSecondary: Color(0xff223338),
    secondaryContainer: Color(0xff3a4c51),
    onSecondaryContainer: Color(0xffa9bbc2),
    tertiary: Color(0xffd7bde8),
    onTertiary: Color(0xff3b284b),
    tertiaryContainer: Color(0xff523e62),
    onTertiaryContainer: Color(0xffc4abd5),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff111415),
    onSurface: Color(0xffe2e2e3),
    onSurfaceVariant: Color(0xffc0c8cb),
    outline: Color(0xff8a9295),
    outlineVariant: Color(0xff40484b),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe2e2e3),
    inversePrimary: Color(0xff346572),
    primaryFixed: Color(0xffb9eafa),
    onPrimaryFixed: Color(0xff001f27),
    primaryFixedDim: Color(0xff9dcede),
    onPrimaryFixedVariant: Color(0xff184d5a),
    secondaryFixed: Color(0xffd3e6ec),
    onSecondaryFixed: Color(0xff0c1e23),
    secondaryFixedDim: Color(0xffb7cad0),
    onSecondaryFixedVariant: Color(0xff38494f),
    tertiaryFixed: Color(0xfff1daff),
    onTertiaryFixed: Color(0xff251335),
    tertiaryFixedDim: Color(0xffd7bde8),
    onTertiaryFixedVariant: Color(0xff533f63),
    surfaceDim: Color(0xff111415),
    surfaceBright: Color(0xff37393a),
    surfaceContainerLowest: Color(0xff0c0f0f),
    surfaceContainerLow: Color(0xff191c1d),
    surfaceContainer: Color(0xff1e2021),
    surfaceContainerHigh: Color(0xff282a2b),
    surfaceContainerHighest: Color(0xff333536),
  );
}
